apiVersion: skaffold/v1beta3
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
  - image: gcr.io/jenkinsxio/builder-base
    context: .
    docker:
      dockerfile: Dockerfile.base
  - image: gcr.io/jenkinsxio/builder-ruby
    context: .
    docker:
      dockerfile: Dockerfile.ruby
  - image: gcr.io/jenkinsxio/builder-swift
    context: .
    docker:
      dockerfile: Dockerfile.swift
test:
- image: docker.io/jenkinsxio/builder-base
  structureTests:
  - ./test-base/*
- image: docker.io/jenkinsxio/builder-ruby:{{.VERSION}}
  structureTests:
  - ./test-ruby/*
deploy:
  kubectl:
    manifests:
profiles:
- name: local
  build:
    local:
      push: false
- name: kaniko
  build:
    kaniko:
      buildContext:
        gcsBucket: jenkinsx-dev-skaffold-kaniko
      pullSecretName: kaniko-secret
      namespace: jx
      timeout: 30m
      image: rawlingsj/executor:dev21
      cache:
        repo: jenkins-x-docker-registry.jx.svc.cluster.local:5000/builder/cache
      dockerConfig:
        secretName: jenkins-docker-cfg
      flags:
      - --cache-dir=/workspace
